#!/usr/bin/env python3
from Docker-python-practiceProject.grsed_core.py import *
import sys

actions = {
    '-r' : (random_characters,int),
    '-e' : (encode_string_64,str),
    '-d' : (decode_string_64,str)
}

input_option = sys.argv[1]
input_value = sys.argv[2]

result = None
try:
    function, parser = actions[input_option]
    result = function(parser(input_value))
except Exception as e:
    print('invalid action')
    exit(1)
    
print(result)
