#!/usr/bin/env python3
import grsed_core.py as grsed
import sys

actions = {
    '-r' : (grsed.random_characters,int),
    '-e' : (grsed.encode_string_64,str),
    '-d' : (grsed.decode_string_64,str)
}

input_option = sys.argv[1]
input_value = sys.argv[2]

result = None
try:
    function, parser = actions[input_option]
    result = function(parser(input_value))
except Exception as e:
    print('invalid action')
    exit(1)
    
print(result)
